use customer_behavior;
select * from customer limit 20;

-- What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue from customer group by gender;

-- Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer where discount_applied = "Yes" and purchase_amount >= (select avg(purchase_amount) from customer) ;

-- Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as "Average Purchase Rating" from customer group by item_purchased order by avg(review_rating) desc limit 5;

-- Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, avg(purchase_amount) from customer where shipping_type in ('Express','Standard') group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id) as "total customers", avg(purchase_amount) as "average revenue", sum(purchase_amount) as "total revenue" from customer group by subscription_status;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, round(sum(case when discount_applied = "Yes" then 1 else 0 end)/count(*) * 100,2) as discount_rate from customer group by item_purchased order by discount_rate desc limit 5;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select case when previous_purchases =1 then 'New'
			when previous_purchases between 2 and 10 then 'Returning'
            else 'Loyal'
            end as customer_segment,
            count(*) as segment_count
		from customer 
        group by customer_segment;
        
-- What are the top 3 most purchased products within each category?
SELECT category, item_purchased, rnk
FROM (
    SELECT 
        category,item_purchased,COUNT(item_purchased) AS item_count,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(item_purchased) DESC) AS rnk
    FROM customer
    GROUP BY category, item_purchased
) AS s
WHERE rnk <= 3;

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer 
where previous_purchases > 5
group by subscription_status;

-- What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue from customer
group by age_group
order by total_revenue desc;
